### ISSUE TITLE
next won't be called in createActivateNext

### ISSUE THREAD

**Issue by menway** [deitch/activator#19]
The 'next' callback will not be called in activator.createActivateNext, don't know why. Could you advise?

activator.createActivateNext(req, res, function() {
  // never hit here
});

**Comment by deitch** [comment]
Hmm, tests all pass, and I just checked that the tests to exercise it. Can you put up a gist with a use case that breaks?

**Comment by menway** [comment]
Ah sorry, it was my fault, i wrote the code in coffee-script and didn't pay attention to the indents. Issue closed. :-)

**Comment by deitch** [comment]
Easy open, easy close! :-)
