### ISSUE TITLE
Question: createActivate function not finding id property

### ISSUE THREAD

**Issue by vinicius0026** [deitch/activator#24]
Hi!
I'm trying to integrate this module into an app, but I'm struggling a little bit.

I'm using the createActivateNext function, which in turn calls the rparams function (only to override the req.params function) and then calls the createActivate function.

This createActivate function tries to find the user id in two places. First it looks into req.activator and then in req.user. But, since the module never actually attached an activator object into the request object, it is unable to find it there. However, the instructions on readme don't say that i'm supposed to attach an user object to request. Am I missing something?

By the way, I did call activator.init(config), which is working, but it doesn't attach anything to request object either.

Thank you in advance! =)

**Comment by vinicius0026** [comment]
I'm sorry, I read readme more carefully and saw it indeed tells explicitly that activator will look in req.user. Closing the issue.

**Comment by deitch** [comment]
Heh, glad it worked out.
