### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by dearfrankg** [deitch/activator#29]
Are the unit tests working?  

npm install
npm test

results in many tests failing for me.

**Comment by deitch** [comment]
I am seeing a clean pass of all test. I just copied the entire repo over, removed `node_modules/`, did a clean `npm install` and then `npm test` and it still passes.

Can you paste `npm ls` here?

Goes without saying, but you have the latest version?

**Comment by dearfrankg** [comment]
Here is the info you requested:

https://gist.github.com/dearfrankg/6a899a123df254579e69

**Comment by dearfrankg** [comment]
Works on ubuntu 

https://gist.github.com/dearfrankg/47fc088b0c3b01feb03d

**Comment by dearfrankg** [comment]
Rebooted my mac fixed it.  Sorry for the trouble.

**Comment by deitch** [comment]
I was about to start comparing `npm ls` to see version differences.

The test probably should randomize the port, rather than use a fixed port. Just never got around to it though.

Glad it worked out in the end.
