### ISSUE TITLE
How does it knows what I want (what user to look for)

### ISSUE THREAD

**Issue by vrghost242** [deitch/activator#31]
Your solution looked absolutely amazing, but I am missing one thing, certain it is really simple:)

I am trying to use the activator on my site, where I implemented mySql to keep track of users (because it seemed like mongo was not painful enough).

So, created all the routes:
```javascript
var cfgWebPage = require('../config/webpage.js');
var bodyParser = require('body-parser');
var activator = require('activator');
var activatorCfg = require('../config/activator.js')
var express = require('express');
var router = express.Router();

activator.init({user: activatorCfg, transport: activatorCfg.smtpUrl , from: activatorCfg.fromEmail, templates: activatorCfg.templatesDir});

//Activation routes
router.post("/", activator.createActivate);
router.put("/:user/active", activator.completeActivate);


//Password reset routes
router.post("/passwordreset",activator.createPasswordReset);
router.put("/:user/passwordreset", activator.completePasswordReset);

router.get('/', function(req, res, next) {
    res.send('respond with a resource');
});



module.exports = router;
```

I then started created a module with all the configuration options, including creating a find function (I know I need the rest of them eventually)
```javascript
module.exports = {
    smtpUrl: "localhost",
    fromEmail: "noreply@localhost.com",
    templatesDir: "/activator-templates",
    find: function(email, done){
        console.log("Was asked to find: " + email );
        done(null, email);
    }
}
```

However, if I send a POST to http://127.0.0.1:30025/activate/ (that is the local url) all I get back is 

HTTP 500 Internal Server Error

Connection: keep-alive
Etag: W/"d-Qt0ac9Byu2vz9JTyKxXbjg"
Content-Type: text/html; charset=utf-8
X-Powered-By: Express
Content-Length: 13
Date: Mon, 04 Jan 2016 17:10:02 GMT

uninitialized

Not certain if that is because the activator.init failes or if that is because I am not sending the right stuff to /activate

**Comment by deitch** [comment]
I see two things here that don't seem right. 

1. The route you are using `/activate/` is not the same as in the expressjs router, where you defined a route for `router.post("/", activator.createActivate);`
2. The `transport` is just a hostname. It needs to be either a nodemailer transport, or a fully-qualified SMTP URL. Check out the README at https://github.com/deitch/activator#transport

Does that help?

**Comment by vrghost242** [comment]
Thank you very much, thought you had hit the nail on the head with the transport.

Changed the code to your example, literally used the string out of the example (smtp://user:pass@mysmtp.com/me.com). For obvious reasons there is no SMTP server that responds to that address currently, still get the same issue. Does activator try to connect to the SMTP server up front?

Triple checked, and the route works, so when I call http://127.0.0.1:30025/activate/ it definitely calls  activator.createActivate. (I wrote it as a seperate route module to avoid disturbing other bits. So there is a statement ```app.use('/activate', activator)``` which strips of the leading activate.


I still have a question that I have not managed to understand, how does createActivate() decide what id or user name to ask for when calling user.find?

**Comment by deitch** [comment]
> Does activator try to connect to the SMTP server up front?

No, it does not. It only tries to connect when it needs to send an email, for example, when you call `createActivate()`.

It finds the user based on the parameters you `POST` to the `createActivate()` call. You can see it here https://github.com/deitch/activator/blob/master/lib/activator.js#L31

It looks for the user ID as a property on the `req` object. See https://github.com/deitch/activator#create-an-activation

By the time you call `createActivate()`, the `req` object should have an `activator` property that is an object with an `id` property. See the example in the README. If you look at the test file in https://github.com/deitch/activator/blob/master/test/test.js you can see an example of it.

FWIW, I have a sample project where I have a POST middleware that takes the email as passed in a form and adds it to the `req` object:

````javascript
req.activator = {id:body,body:body};
````

**Comment by vrghost242** [comment]
First of all, thank you so very much for your help. I do not know how I missed this information the first time around, but I am very VERY grateful for your help.

**Comment by deitch** [comment]
My pleasure. Glad it works.
