### ISSUE TITLE
Issue while sending activation link

### ISSUE THREAD

**Issue by wassimz** [deitch/activator#34]
HI,

I have to integrate your activator library within my project. My project is using sequelize as database ORM. For the moment, I have tried to test the createActivation method. The user activation code was created and added to database successfully but I don't receive any email. As Json response (tested using Postman) I got 404 and 'Not found' message' but no more error message. 

Can you please help me or give me any hints to debug this issues.

Just for information I am using Gmail as smtp mailer support with url like this:
```
url = 'smtps://user%40gmail.com:password@smtp.gmail.com'
```

As IDE I am using Netbeans 8.1 (which supports already Nodejs), but I did not find any way to attach your library source code while debugging.

**Comment by deitch** [comment]
Hi @wassimz 

I am a bit confused. Did you say that the activation code was created and added to the database? Is it that `POST` that is returning `404`, or something else? Did you try and step through the code?

Personally, I just run any node app with `node --debug <file>` and attache `node-inspector`, then use Chrome to step through it. In this case, you might want to walk through https://github.com/deitch/activator/blob/master/lib/activator.js#L77

Maybe you want to put up a gist with your basic startup and route handling code?

**Comment by wassimz** [comment]
Hi @deitch 

Thanks for your fast reply. I have fixed the issue and it was a wrong callback from my side within the save method. 

Regarding the debugging, it seems that Netbeans have its own nodejs debugger and it is not able to stop on node_modules break points. Using node-inspector works like a charm.

But now I have another issue or misconfiguration. Currently I have copied the whole template file that it is under the test file and configured the path correctly. The problem is that currently I receive email with only text and no link. I just received this sentence:

```
This is where everything goes for activate. Please click on the following URL:
```

Is there anythins I am missing it ??

**Comment by deitch** [comment]
Huh, well that is interesting. I used to be a heavy netbeans user (even in the early days of Forte for Java), but never used it for node. Kind of became a real TextMate person over the years.

Put your template and config on a gist and let's see.

**Comment by wassimz** [comment]
@deitch 

I will try to prepare a gist example. But currently I am using the file "activate.txt" which is under "test/resources" folder. I have tried to debug yesterday my issue and it seems that the file is well loaded but when trying to extract the content using the regex pattern (line 77 in mailcomposer.js) it returns only the first line (note that the subject is extracted correctly).

My template file is simple:

```
Activate Email
-------
Please click on the following URL:

<%= request.protocol %>://<%= request.headers.host %>/activate/my/account?code=<%= code %>&email=<%= email %>&user=<%= id %>

Thanks!
```

I don't know what happens. When putting all on the same line, the link is build correctly using the EPS injection. But when adding a return line \n it fails.

Note that I am using windows environment. Does this works only on Linux like system. I have a doubt regarding the \r\n pattern with the regex but I think it is recognized by all environment.

Any helps or hints

**Comment by deitch** [comment]
In theory, I guess it is possible it is a Windows/Linux issue. I have only tried on Mac and Linux.

Try this:

1. Clone the repo `git clone https://github.com/deitch/activator`
2. Install dependences `npm install --dev`
3. Run the tests `npm test`

See what you get. I have never tested on Windows, perhaps there is an issue here and we can figure it out. There is nothing Linux-specific here, but it is possible we are missing something.

**Comment by wassimz** [comment]
@deitch 
I have run unit tests for the module and I got a lot of errors. I have tried to redirect the console output to a file but currently unsuccessfully (I got unrecognized character). So please find below some screeshot of some test cases:

![activator1](https://cloud.githubusercontent.com/assets/1709161/12539227/9f72ac34-c2fe-11e5-9e8b-76eaee1c7576.PNG)
![activator2](https://cloud.githubusercontent.com/assets/1709161/12539228/a0917e42-c2fe-11e5-8fd6-aedf41cdc1a3.PNG)
![activator3](https://cloud.githubusercontent.com/assets/1709161/12539229/a22771e4-c2fe-11e5-95a5-d25e96a23802.PNG)

**Comment by deitch** [comment]
Well, that certainly is helpful. Clearly something strange is going on.

**Comment by deitch** [comment]
OK, I did a complete clean removal of all `node_modules/` and `npm install` on Mac. Just to be absolutely sure it is a Windows thing, and not an npm version thing. Tests run fine.

Do you happen to have a cloud VM available on which I can test it? Or is it all on your laptop? I am willing to spend a bit of time trying to get it to work, but I don't have a Windows machine with node installed with which to work.

**Comment by deitch** [comment]
I found a Windows VM. Yes, the problem 100% is that regex, and it is a Windows vs Linux/Mac/Unix difference.

If you read the same file using `fs.readFile` (or `fs.readFileSync`) on Linux, between each line is a single `\n` character. On Windows, there are **two** characters, `\r\n`.

The git clone onto Windows causes the activate.txt file to have the `\r\n` in it, probably because my git settings are to clone/pull into Windows line-break, but commit to Unix line-break.

The straightforward solution is to have it replace all `\r\n` with `\n` when it reads the file before passing it to a regex, for all mail file reading. I just wonder if there is a more standard way to do it....

**Comment by deitch** [comment]
Tried it. It resolves all except 10 tests. Improvement.

**Comment by deitch** [comment]
OK 1.3.0 is now out. It passes all tests on Linux/Mac and all except 10 on Windows. Try it and put feedback here, please.

**Comment by deitch** [comment]
And they all pass. Done. I am marking this as closed as of 1.3.0. If you still have the issues, please reopen if it is the same issue, else open a new issue.

**Comment by wassimz** [comment]
Thanks. Yes now the body email is send correctly. Thanks for your help

**Comment by deitch** [comment]
Excellent. I am glad it is proving helpful. I was amazed when I looked for a module to do this that no one had. After all, *every* site I have ever been on does this activation and password reset pattern.
