### ISSUE TITLE
completePasswordReset give me 'jwt must be provided'

### ISSUE THREAD

**Issue by vrghost242** [deitch/activator#47]
So I think I am almost there (kind of)

I get the link, send it out, drive the user to a password reset screen, then send a call for the password reset with the new password. All that (I thing is working). My route for completePasswordReset looks like the following:
    router.put('/request/reset/password/:user',activator.completePasswordReset)

So I send the following request to it
```

Request URL:http://127.0.0.1:26021/auth/request/reset/password/bengtbj@gmail.com
Request Method:PUT
Status Code:400 Bad Request
Remote Address:127.0.0.1:26021
Response Headers
view source
Connection:keep-alive
Content-Length:61
Content-Type:application/json; charset=utf-8
Date:Mon, 15 Aug 2016 10:52:58 GMT
ETag:W/"3d-3I3dd1pxBwRmlcv1fhD3sg"
X-Powered-By:Express
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZW5ndGJqQGdtYWlsLmNvbSIsInB1cnBvc2UiOiJyZXNldHBhc3N3b3JkIiwiaWF0IjoxNDcxMjU3ODk2fQ.zwWcuiBa7WIu5PVWrXyvSLrlZobYXLe6KttFXf7Wq8Y
Cache-Control:no-cache
Connection:keep-alive
Content-Length:49
Content-Type:application/json
Cookie:hasConsent=true; incMobileIcon=false; incLinkedinIcon=false; incSkypeIcon=false; incEmailIcon=false; incDirect=false; incMobile=false; incGoogleMapIcon=false; yourmobile=undefined; skype=undefined; direct=undefined; linkedin=undefined; jobname=Marta%20Abrams; jobtitle=CEO%20%26%20Co-founder; jobmail=Marta.Abrams%40unbrand.me; mobile=7507644305; _ga=GA1.1.352163257.1442317669; connect.sid=s%3AbmrERsByqIdLDVoupSGNzyD82MT_boWW.A4mowBtiGNepGgLmandwHuVGf5Tq0npTmcNolko0acw
Host:127.0.0.1:26021
Origin:http://127.0.0.1:26021
Pragma:no-cache
Referer:http://127.0.0.1:26021/request/reset/password?code=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZW5ndGJqQGdtYWlsLmNvbSIsInB1cnBvc2UiOiJyZXNldHBhc3N3b3JkIiwiaWF0IjoxNDcxMjU3ODk2fQ.zwWcuiBa7WIu5PVWrXyvSLrlZobYXLe6KttFXf7Wq8Y&email=bengtbj@gmail.com&user=unBengt
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Request Payload
view source
{email: "bengtbj@gmail.com", password: "newword"}
email
:
"bengtbj@gmail.com"
password
:
"newword"
Name
meassure.png
chromecastcheck.js
data:image/png;base…
bengtbj@gmail.com
```

But I get a 400 error with the message: 
`{"name":"JsonWebTokenError","message":"jwt must be provided"}`

But in the header I do set the code as Authoization, am I missing something?

**Comment by vrghost242** [comment]
I have now tried it with activation as well, and still same issue, it will not read the jwt, or at least it can't find it. 

Tried adding it to header, tried adding it as a url variable (to allow req.query.authorisation) but I just cant get it to work

PUT /auth/request/reset/password/bengtbj@gmail.com?authorization=eyJ0eXAiOiJKV1QiLC...

But I just can't get the thing working. Does anyone have a working example?
This is the call I currently have

   service.callActivate = function(opCode, opUser, opEmail, opPassword){
        console.log("Activating")
        var login = {
            "email": opEmail,
            "password": opPassword,
            "authorization": opCode
        };
        $http({
            method: 'put',
            url: '/auth/request/activate/'+opEmail+'?authorization='+opCode,
            headers: {
                'Content-Type': 'application/json',
                'Authorization': opCode
            },
            data: login

**Comment by vrghost242** [comment]
I'm pretty certain I am doing this wrong somehow, but I am clearly missing something. 
So i edited the params.js a bit just to see what was happening (/activator/lib/params)
So currently mine looks as follows:
```
module.exports = function (req) {
	req.param = function(name, defaultValue){
		console.log("I am looking for " + name)
		var params = this.params || {}, body = this.body || {}, query = this.query || {},
		ret = defaultValue;
		if (params[name] !== null && params[name] !== undefined && params.hasOwnProperty(name)) {
			ret = params[name];
		} else if (body[name] !== null && body[name] !== undefined) {
			console.log("Found " + body[name])
			ret = body[name];
		} else if (query[name] !== null && query[name] !== undefined) {
			ret = query[name];
		}
		return ret;
	};
};

```
And I get the following output:
I am looking for authorization
I am looking for Authorization
Found eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZW5ndGJqQGdtYWlsLmNvbSIsInB1cnBvc2UiOiJyZXNldHBhc3N3b3JkIiwiaWF0IjoxNDcxMzM5OTUwfQ.-MstB7sSot0ymVWno4FQaPUuOZGmXSzBoyJQ7anmbBc
I am looking for user
{"name":"unBrand.me","subsystem":"ACTIVATOR","hostname":"Bengts-MBP-168","pid":47931,"level":30,"msg":"Activator find request for email bengtbj@gmail.com","time":"2016-08-16T11:18:11.704Z","v":0}
{ id: 'unBengt', email: 'bengtbj@gmail.com' }
I am looking for password
Found rest01
> 

So it found the authorisation now, but I still get the following error message: 
{"name":"JsonWebTokenError","message":"jwt must be provided"}

Any ideas

**Comment by deitch** [comment]
Look at the following:

````
Authorization:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZW5ndGJqQGdtYWlsLmNvbSIsInB1cnBvc2UiOiJyZXNldHBhc3N3b3JkIiwiaWF0IjoxNDcxMjU3ODk2fQ.zwWcuiBa7WIu5PVWrXyvSLrlZobYXLe6KttFXf7Wq8Y
````

The README follows the RFC by looking for `Authorization: Bearer <jwt>`

Try that and see if it works?

**Comment by vrghost242** [comment]
Do you have a link to this RFC, tried to send it as 
{email: "Bengt.Bjorkberg@dbfs.co.uk",…}
Authorization
:
"Bearer <eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5ndC5Cam9ya2JlcmdAZGJmcy5jby51ayIsInB1cnBvc2UiOiJhY3RpdmF0aW9uIiwiaWF0IjoxNDcxMzQ3ODk3fQ.kQcPDq8aq8sCRRVhpgNLwYJrQ55RemAfn-ePS0TThzc>"
email
:
"Bengt.Bjorkberg@mail.co.uk"

and without the <> but still no luck

**Comment by deitch** [comment]
Can you repose the last comment with proper formatting so I can see what you did?

**Comment by vrghost242** [comment]
{Now as proper response:) )

So I updated the code so it would send the "Bearer" code 
This is the format of the package

Request Payload: 
```
{email: "Bengt.Bjorkberg@dbfs.co.uk",…}
Authorization
:
"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5ndC5Cam9ya2JlcmdAZGJmcy5jby51ayIsInB1cnBvc2UiOiJhY3RpdmF0aW9uIiwiaWF0IjoxNDcxMzQ5NDA3fQ.cbwn_V9gyWRo41l2gfCtF4B7IYmEzFE8zysuaDNrnSo"
email
:
"Bengt.Bjorkberg@dbfs.co.uk"
```

The response comes back as "invalidcode"
This is what the server end finds (in my modified params.js):  
```
I am looking for authorization
I am looking for Authorization
Found Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5ndC5Cam9ya2JlcmdAZGJmcy5jby51ayIsInB1cnBvc2UiOiJhY3RpdmF0aW9uIiwiaWF0IjoxNDcxMzQ5NDA3fQ.cbwn_V9gyWRo41l2gfCtF4B7IYmEzFE8zysuaDNrnSo
```

**Comment by deitch** [comment]
Nope, not in the payload. In the *header*. The Authorization header should be:

````
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCZW5ndC5Cam9ya2JlcmdAZGJmcy5jby51ayIsInB1cnBvc2UiOiJhY3RpdmF0aW9uIiwiaWF0IjoxNDcxMzQ5NDA3fQ.cbwn_V9gyWRo41l2gfCtF4B7IYmEzFE8zysuaDNrnSo
````

**Comment by vrghost242** [comment]
OK, so now I am even more confused than earlier.
So it seems like it is working (with the Bearer part it seems to call the activator function), but it still returns 400 with invalidcode. However, it is not the same issue as if I send the wrong code. 

So basically, if I use a valid code from the activator, it finds the user, then calls activator, that seems to die without any real reason. If I change the key used for activation (say remove four characters at random), it never calls activator. But there is nothing in my code that would cause a error message "invalidcode"...

This is my activate code: 
```
   activate: function(id,callback){
        var email = id;
        log.info("Received an activation request from " + id)
        if ( email.search("@") === -1 ) {
            log.info("Activator find request for _id " + email);
            var searchCriteria = { '_id': email};
        } else {
            log.info("Activator find request for email " + email);
            var searchCriteria = { 'local.email': email};
        }
        console.log("About to find")
        mgUser.findOne(searchCriteria, function(err, user){
            console.log("Running find")
            if(err){
                log.error("Failed to retrieve data for user " + email+ " error: ",err);
                callback(err, null)
            } else if(!user) {
                log.info("No user found for " + email)
                callback("NO_USER", "");
            } else {
                log.info("User found " + user.alias)
                //console.log(user);
                user.local.activated = true;
                //activated    : { type: Boolean, default: 'false'},
                //console.log(retData)
                user.save( function (err,doc){
                    if(err){
                        log.error(err)
                        callback(err);
                    } else {
                        log.info("Just sending back null for success")
                        callback(null);
                    }
                })
//                callback(null, retData)

            }
        })
    },
```

The server log says: 

> {"name":"unBrand.me","subsystem":"ACTIVATOR","hostname":"Bengts-MBP-168.dbfs.local","pid":1634,"level":30,"msg":"Activator find request for email Bengt.Bjorkberg@dbfs.co.uk","time":"2016-08-16T14:10:25.204Z","v":0}
> { id: 57b318b1a890d92e05f9f8c1,
>   email: 'Bengt.Bjorkberg@dbfs.co.uk' }
> {"name":"unBrand.me","subsystem":"ACTIVATOR","hostname":"Bengts-MBP-168.dbfs.local","pid":1634,"level":30,"msg":"Received an activation request from 57b318b1a890d92e05f9f8c1","time":"2016-08-16T14:10:25.223Z","v":0}

However, I can make the call directly to the module, and it does set it correctly...

**Comment by vrghost242** [comment]
Could someone maybe provide an example of a package sent to the activator that did work, both url, header and body and I should be able to generate the exact same type of put request as a start

**Comment by vrghost242** [comment]
OK, finally managed to figure it out, there was a second problem. 
The id used for .activate is an object not a string, and I did a seach on it carelessly to see if it was a email or id. The initial problem was that header must have Bearer before authentication key.

**Comment by deitch** [comment]
:-)
