### ISSUE TITLE
Custom content of activator template

### ISSUE THREAD

**Issue by AlRezz** [deitch/activator#53]
I have a form, where user enter login, password and info about itself (age, race, sex etc). 
When user submit form send activation email. 
How can add user info (age, race, sex etc) to default activation template?

**Comment by deitch** [comment]
The activation templates use EJS style templates. See this part of the README https://github.com/deitch/activator#templates-format

So you could add a template, for example, like this:

```
Welcome <%= login %>. We see that your age is <%= age %> and you are a <%= sex %>.
```

Those in turn are taken from the available variables (a little further down the README). The following are standard - `code` `authorization` `email` `id` `password` `request`.

You can make a custom property of `request` and store your info there, e.g.

```javascript
request.myapp = {
    login: "jill",
    age: 25,
    sex: "female"
}
```

and thus your template would be:

```
Welcome <%= request.myapp.login %>. We see that your age is <%= request.myapp.age %> and you are a <%= request.myapp.sex %>.
```

**Comment by AlRezz** [comment]
Thanks.
