### ISSUE TITLE
Bug in resetPassword in example

### ISSUE THREAD

**Issue by derekxm** [deitch/activator#58]
In example.js line 48, it should be cb(null, null), otherwise waterfall will not call the next function property.

**Comment by deitch** [comment]
You refer to [here](https://github.com/deitch/activator/blob/master/example.js#L48) ?

**Comment by deitch** [comment]
Oh yes, I see now. Matching the arity to the call. OK, accepted. I think the code should change, not the docs/example.

**Comment by deitch** [comment]
Closed via #60
