### ISSUE TITLE
Concepts explanation

### ISSUE THREAD

**Issue by velascopja** [deitch/activator#67]
First of all, please forgive me if this is an already solved or stupid question. I've read the documentation and the issues for activator and I haven't been able to find any answer to my question.

I'd like to know how to define and use this attributes for the user model:
- activation_code
- password_reset_code
- password_reset_time

I'd also like to know how to check if an activation or reset password code has already been used, in order to avoid using the same code more than once. Does activator check this in any way? If so, how? Or is this check something I have to do on my own?

Thanks in advance for your support.

Best regards.

**Comment by deitch** [comment]
> if this is an already solved or stupid question

No such thing as a stupid question. 

> define and use this attributes for the user model
> * activation_code
> * password_reset_code
> * password_reset_time

Actually, those are out of date. We used to store those in the data store, but now we use JWT signing to track them, so that there is no dependency on a particular data structure. It adds the JWT to the email link, signs it, and then validates it. So it shouldn't matter.

Is the README out of date? I thought we had fixed it.

Oh yes, see [here](https://github.com/deitch/activator#algorithms)

**Comment by deitch** [comment]
Does that help?

**Comment by velascopja** [comment]
Sorry, you're absolutely right. I didn't read with attention enough. Sorry!

What about the second part of the question? Can I read anywhere about checking the use of activation or reset password only once?

Thank you very much.

**Comment by deitch** [comment]
> Sorry

No problem.

> Can I read anywhere about checking the use of activation or reset password only once?

That is a good question. Activation really wouldn't matter, as it is idempotent. If I activate the account `velascopja` once, it is activated. If I do it again, it is... activated. No problem.

> reset password

JWT does make that challenging. We used to store it in the database, we don't anymore, which means the token could be reused. That is an issue. 

Maybe if it included a hash of the current password, or the first 3 chars of the hash, so once it is reset, it will not accept it again? 

Let's close out this issue, and open a new one that explicitly says, "with JWT password reset token can be used more than once." Let's move the conversation there.

**Comment by velascopja** [comment]
Sure Avi. I'm closing this issue and opening the new one.
